import type { Creation, PricingPlan, Review, TailorProfile } from "@/types";

export const tailorProfiles: TailorProfile[] = [
  {
    id: "t1",
    handle: "@atelier-ama",
    atelierName: "Atelier Ama",
    city: "Lomé",
    description:
      "Spécialiste des robes de cérémonie et tenues sur mesure, avec livraison locale et suivi WhatsApp.",
    whatsapp: "+22890000001",
    specialties: ["Robes", "Mariage", "Traditionnel"],
    rating: 4.9,
    reviewsCount: 126,
    completedOrders: 248,
    responseRate: 97,
    heroLabel: "Couture premium pour cérémonies et événements",
    avatarUrl: "/images/landing/cat-traditionnel.jpg",
    coverUrl: "/images/landing/hero-main.jpg",
  },
  {
    id: "t2",
    handle: "@studio-kekeli",
    atelierName: "Studio Kekeli",
    city: "Kara",
    description:
      "Vestes homme, ensembles élégants et coupes contemporaines pensées pour le quotidien et les événements.",
    whatsapp: "+22890000002",
    specialties: ["Homme", "Uniformes", "Enfant"],
    rating: 4.8,
    reviewsCount: 84,
    completedOrders: 173,
    responseRate: 95,
    heroLabel: "Atelier moderne pour silhouettes nettes et fiables",
    avatarUrl: "/images/landing/step-contact.jpg",
    coverUrl: "/images/landing/cat-homme.jpg",
  },
  {
    id: "t3",
    handle: "@mawufe-design",
    atelierName: "Mawufe Design",
    city: "Tsévié",
    description:
      "Créations colorées inspirées des tissus locaux, avec finitions légères adaptées aux usages du quotidien.",
    whatsapp: "+22890000003",
    specialties: ["Traditionnel", "Enfant", "Robes"],
    rating: 4.7,
    reviewsCount: 52,
    completedOrders: 109,
    responseRate: 92,
    heroLabel: "Mode locale expressive, pensée pour le mobile-first",
    avatarUrl: "/images/landing/cat-robes.jpg",
    coverUrl: "/images/landing/cat-traditionnel.jpg",
  },
];

export const creations: Creation[] = [
  {
    id: "c1",
    tailorId: "t1",
    title: "Robe cérémonie corail",
    category: "mariage",
    slug: "robe-ceremonie-corail",
    priceFrom: 45000,
    turnaround: "7 jours",
    likes: 320,
    imageClassName: "from-[#ff8e7f] via-[#ffd6c7] to-[#fff4ee]",
    imageUrl: "/images/landing/cat-robes.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#9E978E",
      accent: "#C59367",
    },
    availableSizes: ["XS", "S", "L", "XL"],
    selectedSize: "S",
    composition: {
      filling: "100% POLYESTER",
      lining: "50% POLYESTER, 50% COTON",
      inner: "100% COTON",
      outerMaterial: "SATIN ET COTON MÉLANGÉS",
    },
    details: [
      "CORAIL DOUX",
      "SILHOUETTE CÉRÉMONIE",
      "POCHES LATÉRALES DISCRÈTES",
      "MANCHES LONGUES",
      "FINITION TAILLÉE MAIN",
      "COL STRUCTURÉ",
    ],
    mediaThumbnails: [
      "Face studio",
      "Silhouette complète",
      "Détail broderie",
      "Vue dos",
    ],
  },
  {
    id: "c2",
    tailorId: "t1",
    title: "Coupe traditionnelle brodée",
    category: "traditionnel",
    slug: "coupe-traditionnelle-brodee",
    priceFrom: 30000,
    turnaround: "5 jours",
    likes: 187,
    imageClassName: "from-[#efb286] via-[#f7d0a9] to-[#fff0db]",
    imageUrl: "/images/landing/cat-traditionnel.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#A3886C",
      accent: "#B87945",
    },
    availableSizes: ["S", "M", "L", "XL"],
    selectedSize: "M",
    composition: {
      filling: "SANS REMBOURRAGE",
      lining: "100% COTON",
      inner: "100% COTON",
      outerMaterial: "WAX ET BRODERIE",
    },
    details: [
      "BEIGE DORÉ",
      "TISSU TRADITIONNEL",
      "BRODERIE AVANT",
      "COUPE AMPLE",
      "POIGNETS BOUTONNÉS",
      "COL CLASSIQUE",
    ],
    mediaThumbnails: [
      "Face à plat",
      "Porté atelier",
      "Détail manche",
      "Vue arrière",
    ],
  },
  {
    id: "c3",
    tailorId: "t2",
    title: "Ensemble homme graphite",
    category: "homme",
    slug: "ensemble-homme-graphite",
    priceFrom: 38000,
    turnaround: "6 jours",
    likes: 205,
    imageClassName: "from-[#596579] via-[#b0b9c8] to-[#edf0f4]",
    imageUrl: "/images/landing/cat-homme.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#8D949A",
      accent: "#A9784F",
    },
    availableSizes: ["S", "M", "L", "XL"],
    selectedSize: "L",
    composition: {
      filling: "SANS REMBOURRAGE",
      lining: "55% POLYESTER, 45% COTON",
      inner: "100% COTON",
      outerMaterial: "GABARDINE COTON",
    },
    details: [
      "GRAPHITE",
      "ENSEMBLE MASCULIN",
      "POCHES PATCH",
      "MANCHES LONGUES",
      "BAS DE VESTE NET",
      "COL TAILLEUR MODERNE",
    ],
    mediaThumbnails: [
      "Face produit",
      "Look complet",
      "Détail col",
      "Vue dos",
    ],
  },
  {
    id: "c4",
    tailorId: "t2",
    title: "Uniforme scolaire premium",
    category: "uniformes",
    slug: "uniforme-scolaire-premium",
    priceFrom: 15000,
    turnaround: "4 jours",
    likes: 112,
    imageClassName: "from-[#6c8aa3] via-[#d2dde8] to-[#f8fbff]",
    imageUrl: "/images/landing/cat-uniformes.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#8FA0AE",
      accent: "#C59367",
    },
    availableSizes: ["XS", "S", "M", "L"],
    selectedSize: "S",
    composition: {
      filling: "SANS REMBOURRAGE",
      lining: "65% POLYESTER, 35% COTON",
      inner: "100% COTON",
      outerMaterial: "POPELINE",
    },
    details: [
      "BLEU PROPRE",
      "TISSU RÉSISTANT",
      "POCHES FONCTIONNELLES",
      "MANCHES LONGUES",
      "BOUTONS RENFORCÉS",
      "COL ÉCOLE CLASSIQUE",
    ],
    mediaThumbnails: [
      "Face produit",
      "Porté enfant",
      "Détail couture",
      "Vue arrière",
    ],
  },
  {
    id: "c5",
    tailorId: "t3",
    title: "Robe enfant wax léger",
    category: "enfant",
    slug: "robe-enfant-wax-leger",
    priceFrom: 12000,
    turnaround: "3 jours",
    likes: 146,
    imageClassName: "from-[#ffbe71] via-[#ffe0b3] to-[#fff7e7]",
    imageUrl: "/images/landing/cat-enfant.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#C7A06C",
      accent: "#C59367",
    },
    availableSizes: ["XS", "S", "M", "L"],
    selectedSize: "XS",
    composition: {
      filling: "SANS REMBOURRAGE",
      lining: "100% COTON",
      inner: "100% COTON",
      outerMaterial: "WAX LÉGER",
    },
    details: [
      "JAUNE CHAUD",
      "TISSU RESPIRANT",
      "COUPE ENFANT",
      "MANCHES COURTES",
      "FINITION DOUCE",
      "COL ROND",
    ],
    mediaThumbnails: [
      "Face produit",
      "Look complet",
      "Détail tissu",
      "Vue dos",
    ],
  },
  {
    id: "c6",
    tailorId: "t3",
    title: "Robe ville fluidité",
    category: "robes",
    slug: "robe-ville-fluidite",
    priceFrom: 22000,
    turnaround: "5 jours",
    likes: 164,
    imageClassName: "from-[#ff8b91] via-[#ffd3d8] to-[#fff6f7]",
    imageUrl: "/images/landing/hero-dress.jpg",
    palette: {
      backgroundMain: "#FFFFFF",
      backgroundSidebar: "#A99997",
      accent: "#C59367",
    },
    availableSizes: ["XS", "S", "L", "XL"],
    selectedSize: "S",
    composition: {
      filling: "SANS REMBOURRAGE",
      lining: "50% POLYESTER, 50% COTON",
      inner: "100% COTON",
      outerMaterial: "CRÊPE FLUIDE",
    },
    details: [
      "ROSE POUDRÉ",
      "TOMBER FLUIDE",
      "POCHES PATCH",
      "MANCHES LONGUES",
      "POIGNETS BOUTONNÉS",
      "COL CLASSIQUE",
    ],
    mediaThumbnails: [
      "Face à plat",
      "Porté silhouette",
      "Détail côté",
      "Vue dos",
    ],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    tailorId: "t1",
    author: "Afi K.",
    rating: 5,
    comment: "Réponse rapide sur WhatsApp, finition très propre et livraison à temps.",
  },
  {
    id: "r2",
    tailorId: "t2",
    author: "Komlan S.",
    rating: 5,
    comment: "Bonne coupe, bon suivi, et prix clair dès le départ.",
  },
  {
    id: "r3",
    tailorId: "t3",
    author: "Yawa M.",
    rating: 4,
    comment: "Très beau rendu final et excellent choix de tissu pour la saison chaude.",
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: "quarterly",
    title: "Plan trimestriel",
    amount: 10000,
    billing: "/ trimestre",
    features: [
      "Profil atelier personnalisé",
      "Galerie photos et vidéos",
      "Lien public partageable",
      "Bouton WhatsApp intégré",
      "Réception des avis clients",
    ],
  },
  {
    id: "yearly",
    title: "Plan annuel",
    amount: 35000,
    billing: "/ an",
    highlighted: true,
    features: [
      "Tout le plan trimestriel",
      "Badge atelier vérifié",
      "Statistiques avancées",
      "Mise en avant dans l’explore",
      "Accès prioritaire aux nouveautés",
    ],
  },
];

